amount_low = "1000000000000000000"
amount_high = "0"
rho = "3"
rcm = "4"
spending_key = "5"
leaf_index = "0"
merkle_siblings = [
  "0", "0", "0", "0", "0",
  "0", "0", "0", "0", "0",
  "0", "0", "0", "0", "0",
  "0", "0", "0", "0", "0"
]
merkle_directions = [
  "0", "0", "0", "0", "0",
  "0", "0", "0", "0", "0",
  "0", "0", "0", "0", "0",
  "0", "0", "0", "0", "0"
]
recipient = "1234"
root = "0"
nullifier_hash = "0"
amount_low_public = "1000000000000000000"
amount_high_public = "0"
